### ISSUE TITLE
Feedback on week 13 project progress for CS2113-T13-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113-T13-4/main#262]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [ ] A suitable deadline set [your deadline: 2019-11-13] (:exclamation:)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @e0318465 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-4/main/issues/184 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @dou-maokang for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-4/main/issues/190 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @gervaiseang for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-4/main/issues/205 https://github.com/AY1920S1-CS2113-T13-4/main/issues/202 https://github.com/AY1920S1-CS2113-T13-4/main/issues/188 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @talesrune for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-4/main/issues/204 https://github.com/AY1920S1-CS2113-T13-4/main/issues/201 https://github.com/AY1920S1-CS2113-T13-4/main/issues/198 https://github.com/AY1920S1-CS2113-T13-4/main/issues/196 https://github.com/AY1920S1-CS2113-T13-4/main/issues/192 https://github.com/AY1920S1-CS2113-T13-4/main/issues/191 https://github.com/AY1920S1-CS2113-T13-4/main/issues/190 https://github.com/AY1920S1-CS2113-T13-4/main/issues/186 https://github.com/AY1920S1-CS2113-T13-4/main/issues/185 https://github.com/AY1920S1-CS2113-T13-4/main/issues/175 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @maxxyx96 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-4/main/issues/203 https://github.com/AY1920S1-CS2113-T13-4/main/issues/178 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @RubaP

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-14 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
